[package]
name = "update-ssh-keys"
version = "0.1.0"
authors = ["Stephen Demos <stephen.demos@coreos.com>"]

[dependencies]
clap = "2.26"
error-chain = { version = "0.11", default-features = false }
fs2 = "0.4"
openssh-keys = "0.1"
users = "0.6"

[profile.release]
lto = true
